### ISSUE TITLE
README.md is out-of-date or incorrect for TypeScript

### ISSUE THREAD

**Issue by monkeycoder99** [rob2d/use-viewport-sizes#17]
You cannot call useViewportSizes with no parameters, you get a compilation error.

Further, you cannot get properly typed parameters when you want only width and height, ignoring the triggerResize value. TypeScript assumes you're expecting the other result type which is dimension, triggerResize. Note, using the following causes eslint issues when you really don't want triggerResize and don't use it in subsequent source.

`
const [vpW, vpH, updateVpSizes] = useViewportSizes();
doSomething(vpW, vpH);
// ignore updateVpSizes
return; // Error will result because updateVpSizes is unused
`

**Comment by rob2d** [comment]
Somehow missed this issue and was not using React for quite some time at a previous employer. Though always open if someone pushes a proposed fix even if I don't have the focus/time at the moment. This should be addressed now that I am a good place to update this lib and work on React applications again for these updates to make sense as a time investment.

For first issue:
> You cannot call useViewportSizes with no parameters, you get a compilation error.

This should be addressed with an update tonight or tomorrow.

For the second issue: 
> const [vpW, vpH, updateVpSizes] = useViewportSizes(); doSomething(vpW, vpH); // ignore updateVpSizes return; // Error will result because updateVpSizes is unused

You should be able to destructure this as `const [vpw, vpH] = useViewportSizes();` without TS complaining as standard practice if you do not need to invoke `updateVpSizes()`.

For further context of source of issues:  to preserve the minimum possible file size without compilation this was written in JS by hand (not usual for me) and `d.ts` is a little interesting; turns out you can override `export default` just by providing multiple defs -- very non-standard in either JS or TS outside of `d.ts` modules, but necessary since Type Inference/Control Flow is limited with types only annotated.

Considering how late this is I would not blame you if you've moved on to using another lib, but would like to comment in case it is useful for anyone else or if you find a need for this library again and thanks for reporting this. Going forward I will be sure to vet TS use-cases now that I have had much more experience and a bit more free time.

**Comment by rob2d** [comment]
Working example on `0.5.1-beta.1` with Typescript project (also demo'ing destructure without triggering TS error) can be found @ https://codesandbox.io/s/tender-dirac-hgd6fe
